spring:
  application:
    name: spring-boot
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # HTML 폼에서 PUT, DELETE 등의 HTTP 메서드를 사용할 수 있도록 설정
  config:
    import: classpath:database.yml # 외부 설정 파일 불러오기
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Hibernate가 MySQL 데이터베이스에 맞는 SQL 문법을 사용하도록 설정
        format_sql: true # 출력되는 SQL 문장을 보기 좋게 줄바꿈과 들여쓰기로 정렬한다
    hibernate:
      ddl-auto: update # 엔티티 클래스에 맞게 DB 테이블을 자동으로 생성하거나 수정 (기존 데이터 유지)
    show-sql: true # 실행되는 SQL 쿼리를 콘솔에 출력

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Hibernate가 실행한 SQL 쿼리를 DEBUG 레벨로 출력
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # SQL 쿼리의 ? 자리에 실제로 어떤 값이 들어갔는지 출력

# 요청과 응답에서 UTF-8 인코딩을 사용하도록 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true