spring.application.name=spring-boot
# \uD55C\uAE00 \uC778\uCF54\uB529 \uC124\uC815
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# MySQL \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815 \uD30C\uC77C import
spring.config.import=classpath:database.properties
# JPA \uAD00\uB828 \uC124\uC815
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# JPA \uB85C\uAE45 \uC124\uC815
# \uB514\uBC84\uADF8 \uB808\uBCA8\uB85C \uCFFC\uB9AC \uCD9C\uB825
logging.level.org.hibernate.SQL=DEBUG
# SQL \uC904\uBC14\uAFC8\uD558\uAE30
spring.jpa.properties.hibernate.format_sql=true
# SQL \uCD9C\uB825 \uD65C\uC131\uD654
spring.jpa.show-sql=true
# \uB9E4\uAC1C\uBCC0\uC218 \uAC12 \uBCF4\uC5EC\uC8FC\uAE30
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE